name: CI NodeJS con cacheo y tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js ⚙️
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.1
        cache: 'npm'

    - name: Cache dependencies ⌛️
      uses: actions/cache@v3
      id: cache-node-modules
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package*.json') }}-${{ hashFiles('.github/workflows/workflow.yml') }}  # Actualizado 'workflow.yml'

    - name: Install dependencies 
      if: steps.cache-node-modules.outputs.cache-hit != 'true'  # Solo instalar si no hay caché
      run: npm install

    - name: Run tests ✅
      run: npm test

    - name: Lint code 
      run: npm run lint
